name: Docker Image CI

on:
  push:
    tags:
      - '**'

jobs:

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: actions/checkout@v3
      - name: Build the Docker image
        env:
          REG: ${{ secrets.REGISTRY_URL }}
          IMG: ${{ secrets.IMAGE_NAME }}
          TAG: ${{ steps.tag.outputs.tag }}
        run: docker build . --file Dockerfile --tag "$REG/$IMG:latest" --tag "$REG/$IMG:$TAG"
      - name: Push image tag
        env:
          REG: ${{ secrets.REGISTRY_URL }}
          IMG: ${{ secrets.IMAGE_NAME }}
          TAG: ${{ steps.tag.outputs.tag }}
        run: docker push "$REG/$IMG:$TAG"
      - name: Push image latest
        env:
          REG: ${{ secrets.REGISTRY_URL }}
          IMG: ${{ secrets.IMAGE_NAME }}
        run: docker push "$REG/$IMG:latest"

  prisma_migrate:
    name: Prisma migrate prod
    needs: build
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Curl portainer
        env:
          URL: ${{ secrets.PORTAINER_MIGRATE_URL }}
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          curl --request POST \
          --url "$URL?tag=$TAG" \

  deploy_prod:
    name: deploy prod
    needs: prisma_migrate
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Curl portainer
        env:
          URL: ${{ secrets.PORTAINER_URL }}
          TAG: ${{ steps.tag.outputs.tag }}
        run: |
          curl --request POST \
          --url "$URL?tag=$TAG" \
