name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '^v[0-9]+(\.[0-9]+)*'
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ice-dev.ru:5000/ron_tayler/fallaf_kr_m_back:latest
    - name: Push image
      run: docker push ice-dev.ru:5000/ron_tayler/fallaf_kr_m_back:latest

